In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
T = tuple(range(10))
T

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [4]:
import numpy as np
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [9]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[3, 9, 2, 9],
       [6, 2, 3, 1],
       [1, 8, 8, 3]])

In [11]:
# Verificando el tipo de dato de array
arr = np.array([1, 2, 3, 4])
print(arr.dtype) 

int64


In [12]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype) 

<U6


In [13]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [15]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr);print(arr.dtype) 

[1 2 3 4]
int32


In [16]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [17]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


In [18]:
Np_cero.ndim

1

In [21]:
Np_random_dimensiones.ndim

2

In [22]:
Np_random_dimensiones.shape

(3, 4)

In [23]:
Np_random_dimensiones.size

12

In [25]:
Np_cero.dtype

dtype('float64')

In [26]:
Np_cero_int.dtype

dtype('int64')

In [27]:
Np_random_dimensiones.itemsize

8

In [28]:
Np_cero.nbytes

80

In [29]:
Np_cero_int.nbytes

80

In [30]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
Np_diez_numeros[0]

1

In [32]:
Np_diez_numeros[4]

5

In [33]:
Np_diez_numeros[-1]

10

In [34]:
Np_diez_numeros[-2]

9

In [35]:
Np_random_dimensiones

array([[3, 9, 2, 9],
       [6, 2, 3, 1],
       [1, 8, 8, 3]])

In [36]:
Np_random_dimensiones[2, 1]

8

In [37]:
Np_diez_numeros[:4]

array([1, 2, 3, 4])

In [38]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [39]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [40]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [41]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

In [42]:
Np_random_dimensiones[2,]

array([1, 8, 8, 3])

In [43]:
Np_random_dimensiones[:2, :2]

array([[3, 9],
       [6, 2]])

In [44]:
Np_random_dimensiones[2, 3]

3

In [45]:
np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [46]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([1, 6, 7, 2, 0, 4, 4, 0, 7, 6])

In [47]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [48]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [49]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [50]:
Arrays_concatenados

array([1, 6, 7, 2, 0, 4, 4, 0, 7, 6])

In [51]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([1, 6]), array([7, 2, 0, 4, 4, 0, 7, 6])]

In [52]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])
Array_partido_2

[array([1, 6]), array([7, 2, 0, 4, 4, 0]), array([7, 6])]

In [53]:
Parte_1, Parte_2, Parte_3 = Array_partido_2
Parte_1

array([1, 6])

In [54]:
Parte_2

array([7, 2, 0, 4, 4, 0])

In [56]:
Parte_3

array([7, 6])

In [57]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4])
Ajedrez_partido_1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]), array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [58]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [59]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)m

[6 3 4 1 2 2 0 3 1 5]


In [60]:
Array_aleatorio.sum()

27

In [61]:
Array_aleatorio.mean()

2.7

In [62]:
Array_aleatorio.max()

6

In [64]:
np.median(Array_aleatorio)

2.5

In [65]:
np.std(Array_aleatorio)

1.7916472867168918

In [66]:
np.var(Array_aleatorio)

3.21

In [67]:
Array_1

array([1, 6, 7, 2, 0])

In [68]:
Array_2


array([4, 4, 0, 7, 6])

In [69]:
Array_1+5

array([ 6, 11, 12,  7,  5])

In [70]:
Array_1 + Array_2

array([ 5, 10,  7,  9,  6])

In [71]:
np.add(Array_1, Array_2)

array([ 5, 10,  7,  9,  6])

In [72]:
np.matmul(Array_1, Array_2)

42

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4f9037d8-f2e9-4683-9ce3-67576f784ec7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>